/* Ketler Simulator
 * Options.java
 * Class to parse the options file for ROM sets

 * Copyright 2011 David Ketler 3394947, Brock University
 *
 * This file is part of the Ketler Simulator.

The Ketler Simulator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Ketler Simulator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Ketler Simulator.  If not, see <http://www.gnu.org/licenses/>.
 */

package _emulator;

import java.io.*;

/**
 *
 * @author dak
 */
public class Options extends javax.swing.JFrame {
    public String s1file1 = "";
    public String s1file2 = "";
    public String s1file3 = "";
    public String s2file1 = "";
    public String s2file2 = "";
    public String s2file3 = "";
    public String s3file1 = "";
    public String s3file2 = "";
    public String s3file3 = "";
    public String s1name = "ROM Set 1";
    public String s2name = "ROM Set 2";
    public String s3name = "ROM Set 3";
    public int selected;

    /** Creates new form Options */
    public Options() {
        initComponents();
        loadSetting();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(_emulator._EmulatorApp.class).getContext().getResourceMap(Options.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText(resourceMap.getString("jRadioButton3.text")); // NOI18N
        jRadioButton3.setName("jRadioButton3"); // NOI18N

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText(resourceMap.getString("jRadioButton4.text")); // NOI18N
        jRadioButton4.setName("jRadioButton4"); // NOI18N

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton4)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton1)
                            .addComponent(jLabel1)
                            .addComponent(jRadioButton2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton1))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.setVisible(false);
}//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        writeSettings();
        this.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jRadioButton2.isSelected()) {
            romOptions op = new romOptions();
            op.setFiles(this, 1);
            op.setVisible(true);
        }
        else if(jRadioButton3.isSelected()) {
            romOptions op = new romOptions();
            op.setFiles(this, 2);
            op.setVisible(true);
        }
        else if(jRadioButton4.isSelected()) {
            romOptions op = new romOptions();
            op.setFiles(this, 3);
            op.setVisible(true);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    public void loadSetting() {
        int equ;
        int num = 0;
        String set;

        File f = new File(("c:/settings.ini"));
        String s;

        try {
            BufferedReader br = new BufferedReader(new FileReader(f));
            while((s = br.readLine()) != null) {
                s.trim();

                if(s.charAt(0) == ';')
                    continue;

                if(s.contains("SET")) {
                    num = s.length() - 2;
                    num = Integer.parseInt(Character.toString(s.charAt(num)));
                    continue;
                }
                
                if(s.contains("name")) {
                    equ = s.indexOf('=') + 1;

                    if(num == 1) {
                        s1name = s.substring(equ,s.length());
                        jRadioButton2.setText(s.substring(equ,s.length())); }
                    else if(num == 2) {
                        s2name = s.substring(equ,s.length());
                        jRadioButton3.setText(s.substring(equ,s.length()));}
                    else if(num == 3) {
                        s3name = s.substring(equ,s.length());
                        jRadioButton4.setText(s.substring(equ,s.length()));
                    }
                }//name if                
                else if(s.contains("file1")) {
                    equ = s.indexOf('=') + 1;

                    if(num == 1)
                        s1file1 = s.substring(equ,s.length());
                    else if(num == 2)
                        s2file1 = s.substring(equ,s.length());
                    else if(num == 3)
                        s3file1 = s.substring(equ,s.length());
                }
                else if(s.contains("file2")) {
                    equ = s.indexOf('=') + 1;
                    if(num == 1)
                        s1file2 = s.substring(equ,s.length());
                    else if(num == 2)
                        s2file2 = s.substring(equ,s.length());
                    else if(num == 3)
                        s3file2 = s.substring(equ,s.length());
                }
                else if(s.contains("file3")) {
                    equ = s.indexOf('=') + 1;
                    if(num == 1)
                        s1file3 = s.substring(equ,s.length());
                    else if(num == 2)
                        s2file3 = s.substring(equ,s.length());
                    else if(num == 3)
                        s3file3 = s.substring(equ,s.length());
                }
                else if(s.contains("selected")) {
                    selected = Integer.parseInt(Character.toString(s.charAt(s.length() - 1)));

                    if(selected == 1)
                        jRadioButton1.setSelected(true);
                    if(selected == 2)
                        jRadioButton2.setSelected(true);
                    if(selected == 3)
                        jRadioButton3.setSelected(true);
                    if(selected == 4)
                        jRadioButton4.setSelected(true);
                }
            }
            br.close();
        }
        catch(Exception e) {}
      
        System.out.println(f.getAbsolutePath());

    }//loadSetting

    public void writeSettings() {
        File f = new File(("c:/settingsTemp.ini"));
        File inF = new File(("c:/settings.ini"));
        String s;

        try {
            BufferedWriter out = new BufferedWriter(new FileWriter(f));
            BufferedReader br = new BufferedReader(new FileReader(inF));

            //write header
            s = br.readLine();
            while (s.charAt(0) == ';') {
                out.write(s +"\n");
                s = br.readLine();
            }

            out.write("[SET 1]\n");
            out.write("name=" + s1name + "\n");
            out.write("file1=" + s1file1 + "\n");
            out.write("file2=" + s1file2 + "\n");
            out.write("file3=" + s1file3 + "\n");
            out.write("[SET 2]\n");
            out.write("name=" + s2name + "\n");
            out.write("file1=" + s2file1 + "\n");
            out.write("file2=" + s2file2 + "\n");
            out.write("file3=" + s2file3 + "\n");
            out.write("[SET 3]\n");
            out.write("name=" + s3name + "\n");
            out.write("file1=" + s3file1 + "\n");
            out.write("file2=" + s3file2 + "\n");
            out.write("file3=" + s3file3 + "\n");

            if(jRadioButton1.isSelected())
                out.write("selected=1");
            if(jRadioButton2.isSelected())
                out.write("selected=2");
            if(jRadioButton3.isSelected())
                out.write("selected=3");
            if(jRadioButton4.isSelected())
                out.write("selected=4");

            out.close();
            br.close();

            BufferedReader temp = new BufferedReader(new FileReader(f));
            BufferedWriter set = new BufferedWriter(new FileWriter(inF));

            while((s = temp.readLine()) != null) {
                set.write(s + "\n");
            }

            set.close();
            temp.close();
        }
        catch(Exception e) {}

        f.delete();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables

    public void update() {
        jRadioButton2.setText(s1name);
        jRadioButton3.setText(s2name);
        jRadioButton4.setText(s3name);
    }
}
