/*
 * Ketler Simulator
 * Motorola 6800 Simulator
 *
 * keyOptions.java
 *
 * options for the keyboard module
 *
 * Copyright 2011 David Ketler 3394947, Brock University
 *
 * This file is part of the Ketler Simulator.

The Ketler Simulator is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Ketler Simulator is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Ketler Simulator.  If not, see <http://www.gnu.org/licenses/>.
 */

package _emulator;
import java.io.*;
import java.util.ArrayList;
import java.awt.FileDialog;


public class pallet extends javax.swing.JFrame {
    public CPU proc;
    public boolean key = false;
    int keyAddress;
    updatePallet updateP = new updatePallet();
    boolean updater = false;
    int offset = 150;

    /** Creates new form pallet */
    public pallet() {
        initComponents();
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_emulator/resources/pallet/displayIcon.png")));
        jButton1.setText("");
        jButton1.setBorderPainted(false);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_emulator/resources/pallet/basicSwitchIcon.png")));
        jButton2.setText("");
        jButton2.setBorderPainted(false);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_emulator/resources/pallet/ledIcon.png")));
        jButton3.setText("");
        jButton3.setBorderPainted(false);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_emulator/resources/pallet/ttyIcon.png")));
        jButton4.setText("");
        jButton4.setBorderPainted(false);
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_emulator/resources/pallet/kbIcon.png")));
        jButton5.setText("");
        jButton5.setBorderPainted(false);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jToolBar1 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        palletP1 = new _emulator.palletP();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();

        jFileChooser1.setName("jFileChooser1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(_emulator._EmulatorApp.class).getContext().getResourceMap(pallet.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        jToolBar1.setRollover(true);
        jToolBar1.setName("jToolBar1"); // NOI18N

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/_emulator/resources/Display/displayIcon.png"))); // NOI18N
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setName("jButton1"); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton1);

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setName("jButton3"); // NOI18N
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setName("jButton4"); // NOI18N
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton4);

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setFocusable(false);
        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton5.setName("jButton5"); // NOI18N
        jButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton5);

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setName("jButton6"); // NOI18N
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        palletP1.setName("palletP1"); // NOI18N

        javax.swing.GroupLayout palletP1Layout = new javax.swing.GroupLayout(palletP1);
        palletP1.setLayout(palletP1Layout);
        palletP1Layout.setHorizontalGroup(
            palletP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        palletP1Layout.setVerticalGroup(
            palletP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        jMenuBar1.setName("jMenuBar1"); // NOI18N

        jMenu1.setText(resourceMap.getString("jMenu1.text")); // NOI18N
        jMenu1.setName("jMenu1"); // NOI18N

        jMenuItem1.setText(resourceMap.getString("jMenuItem1.text")); // NOI18N
        jMenuItem1.setName("jMenuItem1"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText(resourceMap.getString("jMenuItem2.text")); // NOI18N
        jMenuItem2.setName("jMenuItem2"); // NOI18N
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem4.setText(resourceMap.getString("jMenuItem4.text")); // NOI18N
        jMenuItem4.setName("jMenuItem4"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem3.setText(resourceMap.getString("jMenuItem3.text")); // NOI18N
        jMenuItem3.setName("jMenuItem3"); // NOI18N
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(palletP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(palletP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        palletP1.proc = proc;
        palletP1.addButtons("display");
        palletP1.updateUI();
        startUpdater();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        palletP1.proc = proc;
        palletP1.addButtons("switch");
        palletP1.updateUI();
        startUpdater();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        jFileChooser1.setApproveButtonText("Save");
        int returnVal = jFileChooser1.showOpenDialog(this);
        File file = jFileChooser1.getSelectedFile();
        

        //FileDialog d = new FileDialog(this);
        //d.setVisible(true);
        //File file = new File(d.getFile());
        System.out.println(file.getAbsolutePath());
        palletP1.save(file);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jFileChooser1.setApproveButtonText("Load");
        int returnVal = jFileChooser1.showOpenDialog(this);
        File file = jFileChooser1.getSelectedFile();

        palletP1.load(file);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        palletP1.reset();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        palletP1.proc = proc;
        palletP1.addButtons("LED");
        palletP1.updateUI();
        startUpdater();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        palletP1.proc = proc;
        palletP1.addTeletype();
        palletP1.updateUI();
        startUpdater();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        if(key) {
            System.out.println(evt.getKeyChar() + "  " +(int)evt.getKeyChar());
            proc.mem[keyAddress] = (byte)evt.getKeyChar();
            System.out.println(Integer.toHexString(keyAddress));
            proc.updated = true;

            ArrayList<button> l = palletP1.list;
            for(int i = 0; i < l.size(); i++) {
                if(l.get(i).type.compareTo("kb") == 0) {
                    if(l.get(i).irq == 1)
                        proc.MI = true;
                    else if(l.get(i).irq == 2)
                        proc.NMI = true;

                    proc.updated = true;
                }//irq if
            }//loop for keyboard
        }
    }//GEN-LAST:event_formKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        palletP1.proc = proc;
        palletP1.p = this;
        palletP1.addButtons("kb");
        palletP1.updateUI();
        startUpdater();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        button b = new button("");
        int x,y;
        x = y = offset;
        
        palletP1.proc = proc;
        palletP1.addButtons("key",'d');
        palletP1.addButtons("key",'e');
        palletP1.addButtons("key",'f');
        palletP1.addButtons("key",'a');
        palletP1.addButtons("key",'b');
        palletP1.addButtons("key",'c');
        palletP1.addButtons("key",'7');
        palletP1.addButtons("key",'8');
        palletP1.addButtons("key",'9');
        palletP1.addButtons("key",'4');
        palletP1.addButtons("key",'5');
        palletP1.addButtons("key",'6');
        palletP1.addButtons("key",'1');
        palletP1.addButtons("key",'2');
        palletP1.addButtons("key",'3');
        palletP1.addButtons("key",'0');
        
        ArrayList<button> l = palletP1.list;
        for(int i = 16; i > 0; i--) {
            if(i == 13 || i == 10 || i == 7 || i == 4 || i == 1) {
                y = y + 60;
                x = offset;
            }
            if(i == 1) {
                x = x + 60;
            }

            b = l.get(l.size() - i);
            b.setLocation(x,y);
            b.proc = proc;
            x = x + 60;
        }

        palletP1.addButtons("displayEt");
        palletP1.addButtons("displayEt");
        palletP1.addButtons("displayEt");
        palletP1.addButtons("displayEt");
        palletP1.addButtons("displayEt");
        palletP1.addButtons("displayEt");
        l = palletP1.list;
        int off = 75;
        for(int i = l.size() - 1; i > 0; i--) {
            b = l.get(i);
            if(b.type.compareTo("displayEt") == 0) {
                b.setLocation(b.getX()+off,b.getY());
            }
            off = off + 75;
        }

        palletP1.updateUI();
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * getObjs
     * returns an int array representing the objects in the pallet
     * in the following form:
     * memory address
     * IRQ
     * Kind of pallet object: 0 Display, 1 Switch
     * @return int[]
     */
    public int[] getObjs() {
       ArrayList<button> l = palletP1.list;
       int[] objs = new int[l.size()*3];

       for(int i = 0; i < l.size(); i++) {  
           objs[i*3] = l.get(i).mem;
           objs[i*3 + 1] = l.get(i).irq;
           objs[i*3 + 2] = l.get(i).kind;
       }

       return objs;
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pallet().setVisible(true);
            }
        });
    }

    public void setCPU(CPU p) {
        proc = p;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JToolBar jToolBar1;
    private _emulator.palletP palletP1;
    // End of variables declaration//GEN-END:variables

    private void startUpdater() {
        if(updater)
            return;
        else {
            try {
                Thread updateInterface = new Thread(updateP);
                updateP.p = palletP1;
                updateP.processor = proc;
                updateInterface.start();
            } catch (Exception e) {
                System.out.println(e.toString());
            }
            updater = true;
        }
    }//startUpdater

}//class
